// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6dAR_gajtIphJ6C96xhRXOFhzsKtMFrw',
    appId: '1:380087449363:web:be8788f1dbc64807488ce6',
    messagingSenderId: '380087449363',
    projectId: 'rutetikuspab',
    authDomain: 'rutetikuspab.firebaseapp.com',
    storageBucket: 'rutetikuspab.firebasestorage.app',
    measurementId: 'G-51S3EQFJ8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEHyDIEdny4Tdi5zCR7GxREz9Ei0iR2Hc',
    appId: '1:380087449363:android:9450f8a6fbf2c576488ce6',
    messagingSenderId: '380087449363',
    projectId: 'rutetikuspab',
    storageBucket: 'rutetikuspab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEeygP8jq3jQAcQrEA9SqG6Y8GHijJc58',
    appId: '1:380087449363:ios:0c3d1fef6b87360e488ce6',
    messagingSenderId: '380087449363',
    projectId: 'rutetikuspab',
    storageBucket: 'rutetikuspab.firebasestorage.app',
    iosBundleId: 'com.example.ruteTikus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEeygP8jq3jQAcQrEA9SqG6Y8GHijJc58',
    appId: '1:380087449363:ios:0c3d1fef6b87360e488ce6',
    messagingSenderId: '380087449363',
    projectId: 'rutetikuspab',
    storageBucket: 'rutetikuspab.firebasestorage.app',
    iosBundleId: 'com.example.ruteTikus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6dAR_gajtIphJ6C96xhRXOFhzsKtMFrw',
    appId: '1:380087449363:web:b01a441f2a7d9c51488ce6',
    messagingSenderId: '380087449363',
    projectId: 'rutetikuspab',
    authDomain: 'rutetikuspab.firebaseapp.com',
    storageBucket: 'rutetikuspab.firebasestorage.app',
    measurementId: 'G-RS5JHK2C95',
  );
}
